language: cpp
compiler:
  - gcc
install:
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install ncurses-dev
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
script:
  - make CFLAGS='-std=c++0x -O3'